#! /bin/sh
### BEGIN INIT INFO
# Provides:          eng10032lab03_2
# Required-Start:    
# Should-Start:      
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO for Lab 03.
# Description:       Configures GPIO for Lab 03.
### END INIT INFO

case "$1" in
    start|restart|force-reload)

	# verifica se existe o diretorio da GPIO 46
	if [ ! -d /sys/class/gpio/gpio76 ] ; then
		# se não existe, faz a exportação
	    echo -n "76" > /sys/class/gpio/export
	fi
	#configura o valor da porta
	echo -n "0" > /sys/class/gpio/gpio76/value

	if [ ! -d /sys/class/gpio/gpio64 ] ; then
	    echo -n "64" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio64/direction
	echo -n "0" > /sys/class/gpio/gpio64/value

	if [ ! -d /sys/class/gpio/gpio62 ] ; then
	    echo -n "62" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio62/direction

	# muda a permissão para o grupo gpio poder ler e escrever na porta gpio62
	chgrp gpio /sys/class/gpio/gpio62/value
	chmod g+rw /sys/class/gpio/gpio62/value
	;;


    stop)
	# "desexporta" as portas usadas e bota como valor padrão"
    	echo -n "in" > /sys/class/gpio/gpio62/direction
    	echo -n "62" > /sys/class/gpio/unexport
		echo -n "76" > /sys/class/gpio/unexport
		echo -n "64" > /sys/class/gpio/unexport
	;;
    status)
    	ls -d /sys/class/gpio/gpio*
	;;
    *)
	echo -n "Usage: $0 " 
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
