#! /bin/sh
### BEGIN INIT INFO
# Provides:          eng10032lab07_1
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO and ADC for Lab 07.
# Description:       Configures GPIO and ADC for Lab 07.
### END INIT INFO

case "$1" in
    start|restart|force-reload)

	# gpio49 = in = neither pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio49 ] ; then
	    echo -n "49" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio49/direction

    chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage0_raw
    chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_raw
    chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage0_scale
    chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_scale

    # gpio62 = in = neither pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio62 ] ; then
	    echo -n "62" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio62/direction

    chgrp gpio /sys/class/gpio/gpio62/value
    chmod g+rw /sys/class/gpio/gpio62/value

    # gpio17 = in = neither pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio17 ] ; then
	    echo -n "17" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio17/direction

    # gpio76 = in = neither pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio76 ] ; then
	    echo -n "76" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio76/direction
    echo -n "0" > /sys/class/gpio/gpio62/value

    # gpio64 = in = neither pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio64 ] ; then
	    echo -n "64" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio64/direction
    echo -n "0" > /sys/class/gpio/gpio62/value

    	;;
    stop)

	echo -n "49" > /sys/class/gpio/unexport
    echo -n "17" > /sys/class/gpio/unexport
    echo -n "62" > /sys/class/gpio/unexport
    echo -n "64" > /sys/class/gpio/unexport
    echo -n "76" > /sys/class/gpio/unexport
    echo -n "in" > /sys/class/gpio62/direction
	;;
    status)
	;;
    *)
	echo -n "Usage: $0 "
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
