#! /bin/sh
### BEGIN INIT INFO
# Provides:          eng10032lab07_2
# Required-Start:    
# Should-Start:      
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO and ADC for Lab 07.
# Description:       Configures GPIO and ADC for Lab 07.
### END INIT INFO

case "$1" in
    start|restart|force-reload)
	# gpio49 = in = neither pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio49 ] ; then
	    echo -n "49" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio49/direction
        

	chgrp p2micros /sys/bus/iio/devices/iio:device0/in_voltage0_scale
	chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_scale
	
	chgrp p2micros /sys/bus/iio/devices/iio:device0/scan_elements/in_voltage0_en
	chmod g+rw /sys/bus/iio/devices/iio:device0/scan_elements/in_voltage0_en


	chgrp p2micros /sys/bus/iio/devices/iio:device0/scan_elements/in_timestamp_en
	chmod g+rw /sys/bus/iio/devices/iio:device0/scan_elements/in_timestamp_en
	
	chgrp p2micros /sys/bus/iio/devices/iio:device0/buffer/enable
	chmod g+rw /sys/bus/iio/devices/iio:device0/buffer/enable
	chgrp p2micros /sys/bus/iio/devices/iio:device0/buffer/length
	chmod g+rw /sys/bus/iio/devices/iio:device0/buffer/length
		
	modprobe iio-trig-hrtimer
	echo -n "0" > /sys/bus/iio/devices/iio_hrtimer_trigger/add_trigger
	
	chgrp p2micros /sys/bus/iio/devices/trigger0/frequency
	chmod g+rw /sys/bus/iio/devices/trigger0/frequency
	
	chgrp p2micros /sys/bus/iio/devices/iio:device0/trigger/current_trigger
	chmod g+rw /sys/bus/iio/devices/iio:device0/trigger/current_trigger
	
	chgrp p2micros /dev/iio:device0
	chmod g+r /dev/iio:device0
    	;;
    stop)
	echo "\n" > /sys/bus/iio/devices/iio:device0/trigger/current_trigger
	
	echo -n "0" > /sys/bus/iio/devices/iio_hrtimer_trigger/remove_trigger
	rmmod iio-trig-hrtimer
	
	echo -n "49" > /sys/class/gpio/unexport
	;;
    status)
    	cat /sys/bus/iio/devices/iio:device0/trigger/current_trigger
	;;
    *)
	echo -n "Usage: $0 " 
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
