#! /bin/sh
### BEGIN INIT INFO
# Provides:          libgalileo2_service
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures the libgalileo2_service functionalities
# Description:       Configures the libgalileo2_service functionalities
### END INIT INFO

case "$1" in
    start|restart|force-reload)

		#############################
		#	DIGITAL PIN MAP (DEFAULT)
		#   
		#   IO2 => Led
		#   IO3 => PWM1
		#	IO4 =>
		#	IO5 => 
		#	IO6 => Button
		#
		#############################

		#############################
		#	ADC PIN MAP (DEFAULT)
		#   
		#   TRIGGER0 => hrtimer (HW)
		#
		#   AD0 => CONTINUOUS
		#   AD1 => CONTINUOUS
		#	AD2 => ONE SHOT
		#	AD3 => ONE SHOT
		#
		#############################

		## Begin of pwm stuff ##

			chgrp p2micros /sys/class/pwm/pwmchip0/device/pwm_period
			chmod g+w /sys/class/pwm/pwmchip0/device/pwm_period

		## End of pwm stuff ##

		## Begin of IO2 ##
		# As a output LED

			if [ ! -d /sys/class/gpio/gpio61 ] ; then
				echo -n "61" > /sys/class/gpio/export
			fi
			echo -n "out" > /sys/class/gpio/gpio61/direction

			if [ ! -d /sys/class/gpio/gpio34 ] ; then
				echo -n "34" > /sys/class/gpio/export
			fi
			echo -n "out" > /sys/class/gpio/gpio34/direction
			echo -n "0" > /sys/class/gpio/gpio34/value

			if [ ! -d /sys/class/gpio/gpio77 ] ; then
				echo -n "77" > /sys/class/gpio/export
			fi
			echo -n "0" > /sys/class/gpio/gpio77/value
			
			chgrp p2micros /sys/class/gpio/gpio61/value
			chmod g+rw /sys/class/gpio/gpio61/value
			chgrp p2micros /sys/class/gpio/gpio61/edge
			chmod g+rw /sys/class/gpio/gpio61/edge

		## End of IO2 ##

		## Begin of IO3 (PWM1) ##
		# As a output SERVO

			if [ ! -d /sys/class/pwm/pwmchip0/pwm1 ] ; then
				echo -n "1" > /sys/class/pwm/pwmchip0/export
			fi
			
			chgrp p2micros /sys/class/pwm/pwmchip0/pwm1/duty_cycle
			chmod g+w /sys/class/pwm/pwmchip0/pwm1/duty_cycle
			chgrp p2micros /sys/class/pwm/pwmchip0/pwm1/enable
			chmod g+w /sys/class/pwm/pwmchip0/pwm1/enable

			# gpio16 = 0 = out
			if [ ! -d /sys/class/gpio/gpio16 ] ; then
				echo -n "16" > /sys/class/gpio/export
			fi
			echo -n "out" > /sys/class/gpio/gpio16/direction
			echo -n "0" > /sys/class/gpio/gpio16/value

			# gpio17 = in = no pull-up nor pull-down
			if [ ! -d /sys/class/gpio/gpio17 ] ; then
				echo -n "17" > /sys/class/gpio/export
			fi
			echo -n "in" > /sys/class/gpio/gpio17/direction

			if [ ! -d /sys/class/gpio/gpio76 ] ; then
				echo -n "76" > /sys/class/gpio/export
			fi
			echo -n "0" > /sys/class/gpio/gpio76/value


			# gpio64 = 1 */
			if [ ! -d /sys/class/gpio/gpio64 ] ; then
				echo -n "64" > /sys/class/gpio/export
			fi
			echo -n "1" > /sys/class/gpio/gpio64/value


		## End of IO3 (PWM1) ##


		## Begin of IO5 (PWM3) ##
		# As a output SERVO

			if [ ! -d /sys/class/pwm/pwmchip0/pwm3 ] ; then
				echo -n "3" > /sys/class/pwm/pwmchip0/export
			fi
			
			chgrp p2micros /sys/class/pwm/pwmchip0/pwm3/duty_cycle
			chmod g+w /sys/class/pwm/pwmchip0/pwm3/duty_cycle
			chgrp p2micros /sys/class/pwm/pwmchip0/pwm3/enable
			chmod g+w /sys/class/pwm/pwmchip0/pwm3/enable

			# gpio18 = 0 = out
			if [ ! -d /sys/class/gpio/gpio18 ] ; then
				echo -n "18" > /sys/class/gpio/export
			fi
			echo -n "out" > /sys/class/gpio/gpio18/direction
			echo -n "0" > /sys/class/gpio/gpio18/value

			# gpio19 = in = no pull-up nor pull-down
			if [ ! -d /sys/class/gpio/gpio19 ] ; then
				echo -n "19" > /sys/class/gpio/export
			fi
			echo -n "in" > /sys/class/gpio/gpio19/direction

			if [ ! -d /sys/class/gpio/gpio66 ] ; then
				echo -n "66" > /sys/class/gpio/export
			fi
			echo -n "1" > /sys/class/gpio/gpio66/value

		## End of IO5 (pwm3) ##

		## Begin of IO6 ##
		# As a input button

			if [ ! -d /sys/class/gpio/gpio1 ] ; then
				echo -n "1" > /sys/class/gpio/export
			fi
			echo -n "in" > /sys/class/gpio/gpio1/direction
			
			if [ ! -d /sys/class/gpio/gpio20 ] ; then
				echo -n "20" > /sys/class/gpio/export
			fi
			echo -n "out" > /sys/class/gpio/gpio20/direction
			echo -n "1" > /sys/class/gpio/gpio20/value

			if [ ! -d /sys/class/gpio/gpio21 ] ; then
				echo -n "21" > /sys/class/gpio/export
			fi
			echo -n "out" > /sys/class/gpio/gpio21/direction
			echo -n "0" > /sys/class/gpio/gpio21/value
			
			if [ ! -d /sys/class/gpio/gpio68 ] ; then
				echo -n "68" > /sys/class/gpio/export
			fi
			echo -n "0" > /sys/class/gpio/gpio68/value
			
			chgrp p2micros /sys/class/gpio/gpio1/value
			chmod g+rw /sys/class/gpio/gpio1/value
			chgrp p2micros /sys/class/gpio/gpio1/edge
			chmod g+rw /sys/class/gpio/gpio1/edge


		## End of IO6 ##

		

		## Begin of continuous stuff

			hgrp p2micros /sys/bus/iio/devices/iio:device0/scan_elements/in_timestamp_en
			chmod g+rw /sys/bus/iio/devices/iio:device0/scan_elements/in_timestamp_en
			
			chgrp p2micros /sys/bus/iio/devices/iio:device0/buffer/enable
			chmod g+rw /sys/bus/iio/devices/iio:device0/buffer/enable
			chgrp p2micros /sys/bus/iio/devices/iio:device0/buffer/length
			chmod g+rw /sys/bus/iio/devices/iio:device0/buffer/length
				
			modprobe iio-trig-hrtimer
			echo -n "0" > /sys/bus/iio/devices/iio_hrtimer_trigger/add_trigger
			
			chgrp p2micros /sys/bus/iio/devices/trigger0/frequency
			chmod g+rw /sys/bus/iio/devices/trigger0/frequency
			
			chgrp p2micros /sys/bus/iio/devices/iio:device0/trigger/current_trigger
			chmod g+rw /sys/bus/iio/devices/iio:device0/trigger/current_trigger
			
			chgrp p2micros /dev/iio:device0
			chmod g+r /dev/iio:device0

		## End of continuous stuff

		## Begin of AD 0 ## 

			 #gpio49 = in = neither pull-up nor pull-down
			if [ ! -d /sys/class/gpio/gpio49 ] ; then
				echo -n "49" > /sys/class/gpio/export
			fi
			echo -n "in" > /sys/class/gpio/gpio49/direction


			chgrp p2micros /sys/bus/iio/devices/iio:device0/in_voltage0_scale
			chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_scale
				
			#	Continuous
			chgrp p2micros /sys/bus/iio/devices/iio:device0/scan_elements/in_voltage0_en
			chmod g+rw /sys/bus/iio/devices/iio:device0/scan_elements/in_voltage0_en

			# 	One-shot
			#chgrp adc /sys/bus/iio/devices/iio:device0/scan_elements/in_voltage0_en
			#chmod g+rw /sys/bus/iio/devices/iio:device0/scan_elements/in_voltage0_en


			
			
		## End of AD 0 ##

		## Begin of AD 1 ## 

			# gpio51 = in = neither pull-up nor pull-down
			if [ ! -d /sys/class/gpio/gpio51 ] ; then
				echo -n "51" > /sys/class/gpio/export
			fi
			echo -n "in" > /sys/class/gpio/gpio51/direction

			chgrp p2micros /sys/bus/iio/devices/iio:device0/in_voltage1_scale
			chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage1_scale
				
			#	Continuous
			chgrp p2micros /sys/bus/iio/devices/iio:device0/scan_elements/in_voltage1_en
			chmod g+rw /sys/bus/iio/devices/iio:device0/scan_elements/in_voltage1_en

			# 	One-shot
			#	chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage1_raw
			#	chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage1_raw

			 
			
		## End of AD 1 ##

		## Begin of AD 2 ## 

			# gpio53 = in = neither pull-up nor pull-down
			if [ ! -d /sys/class/gpio/gpio53 ] ; then
				echo -n "53" > /sys/class/gpio/export
			fi
			echo -n "in" > /sys/class/gpio/gpio53/direction
			
			chgrp p2micros /sys/bus/iio/devices/iio:device0/in_voltage2_raw
			chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage2_raw
			chgrp p2micros /sys/bus/iio/devices/iio:device0/in_voltage2_scale
			chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage2_scale

			
			
		## End of AD 2 ##

		## Begin of AD 3 ## 

			# gpio55 = in = neither pull-up nor pull-down
			if [ ! -d /sys/class/gpio/gpio55 ] ; then
				echo -n "55" > /sys/class/gpio/export
			fi
			echo -n "in" > /sys/class/gpio/gpio55/direction
				
			chgrp p2micros /sys/bus/iio/devices/iio:device0/in_voltage3_raw
			chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage3_raw
			chgrp p2micros /sys/bus/iio/devices/iio:device0/in_voltage3_scale
			chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage3_scale
			
		## End of AD 3 ##

		## Begin of EEPROM ##
			chgrp p2micros /sys/bus/i2c/devices/0-0054/eeprom
			chmod g+rw /sys/bus/i2c/devices/0-0054/eeprom
		## End of EEPROM ##

		## Begin of LCD ##
			# Pull-up on IO18
			if [ ! -d /sys/class/gpio/gpio57 ] ; then
				echo -n "57" > /sys/class/gpio/export
			fi
			echo "out" > /sys/class/gpio/gpio57/direction
			echo "1" > /sys/class/gpio/gpio57/value

			# Select I2C on IO18 and IO19
			if [ ! -d /sys/class/gpio/gpio60 ] ; then
				echo -n "60" > /sys/class/gpio/export
			fi
			echo "out" > /sys/class/gpio/gpio60/direction
			echo "0" > /sys/class/gpio/gpio60/value

			# Pull-up on IO19
			if [ ! -d /sys/class/gpio/gpio59 ] ; then
				echo -n "59" > /sys/class/gpio/export
			fi
			echo "out" > /sys/class/gpio/gpio59/direction
			echo "1" > /sys/class/gpio/gpio59/value

			chgrp p2micros /dev/i2c-0
			chmod g+rw /dev/i2c-0
		## End of LCD ##

		
	;;
    stop)

		## Begin of IO3 (PWM1) ## 
			echo -n "0" > /sys/class/pwm/pwmchip0/pwm1/enable
			echo -n "76" > /sys/class/gpio/unexport
			echo -n "64" > /sys/class/gpio/unexport
			echo -n "17" > /sys/class/gpio/unexport
			echo -n "1" > /sys/class/gpio/gpio16/value
			echo -n "16" > /sys/class/gpio/unexport
			echo -n "1" > /sys/class/pwm/pwmchip0/unexport
		## End of IO3 ## 

		## Begin of IO3 (LED) ## 
			#echo -n "in" > /sys/class/gpio/gpio62/direction
			#echo -n "62" > /sys/class/gpio/unexport
			#echo -n "76" > /sys/class/gpio/unexport
			#echo -n "64" > /sys/class/gpio/unexport
		## End of IO3 ## 

		## Begin of IO5 (PWM3) ## 
			echo -n "0" > /sys/class/pwm/pwmchip0/pwm3/enable
			echo -n "1" > /sys/class/gpio/unexport
			echo -n "20" > /sys/class/gpio/unexport
			echo -n "1" > /sys/class/gpio/gpio18/value
			echo -n "68" > /sys/class/gpio/unexport
			echo -n "3" > /sys/class/pwm/pwmchip0/unexport
		## End of IO5 ## 

		## Begin of IO6 (LED) ## 
			echo -n "18" > /sys/class/gpio/unexport
			echo -n "19" > /sys/class/gpio/unexport
			echo -n "66" > /sys/class/gpio/unexport
		## End of IO6 ## 


		## Begin of AD 0 ## 
			echo -n "49" > /sys/class/gpio/unexport

			# Begin of Continuous 
				echo "\n" > /sys/bus/iio/devices/iio:device0/trigger/current_trigger
	
				echo -n "0" > /sys/bus/iio/devices/iio_hrtimer_trigger/remove_trigger
				rmmod iio-trig-hrtimer

			# End of continuous 

		## End of AD 0 ## 

		## Begin of AD 1 ## 
			echo -n "51" > /sys/class/gpio/unexport
		## End of AD 1 ## 

		## Begin of AD 3 ## 
			echo -n "53" > /sys/class/gpio/unexport
		## End of AD 3 ## 

		## Begin of AD 4 ## 
			echo -n "55" > /sys/class/gpio/unexport
		## End of AD 4 ## 

		## Begin of LCD ##
			# No pull-up on IO18
			echo "in" > /sys/class/gpio/gpio57/direction
			echo "57" > /sys/class/gpio/unexport

			# GPIO on IO18 and IO19
			echo "1" > /sys/class/gpio/gpio60/value
			echo "60" > /sys/class/gpio/unexport

			# No pull-up on  IO19
			echo "in" > /sys/class/gpio/gpio59/direction
			echo "59" > /sys/class/gpio/unexport
		## End of LCD ##

		
	;;
    status)
		## Begin of IO3 (pwm1) ##
			echo -n Period:
			cat /sys/class/pwm/pwmchip0/device/pwm_period
			echo -n Duty Cicle:
			cat /sys/class/pwm/pwmchip0/pwm1/duty_cycle
			echo -n Enable:
			cat /sys/class/pwm/pwmchip0/pwm1/enable

			cat /sys/bus/iio/devices/iio:device0/trigger/current_trigger
		## End of IO3 (pwm1) ##
	;;
    *)
	echo -n "Usage: $0 "
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0